import { test, expect, request } from '@playwright/test';
import { clearTestUser, clearTestOrders, getFirstInvoiceForUser, getSeededProductId } from './helpers/db';

// ============================================================================
// Suite 9: Invoice — Generation and Download
// Tests the post-payment invoice lifecycle:
//   1. Register → Login → Add to Cart → Create Order → Create Payment Intent
//   2. Verify payment with the built-in mock signature so invoice auto-generates.
//   3. Assert GET /api/v1/invoices returns a non-empty list with the new invoice.
//   4. Assert GET /api/v1/invoices/:id/download returns HTTP 200 with a valid PDF.
//   5. UI test: Account > Invoices tab shows the invoice row and Download button.
// ============================================================================

const TEST_EMAIL = 'test_invoice_flow@eyeware.test';
const TEST_PASSWORD = 'InvoiceTest456!';
const API_BASE = 'http://localhost:3000';

test.describe('Suite 9: Invoice', () => {
  let authCookie = '';
  let invoiceId = 0;

  test.beforeAll(async () => {
    // Clean any previous run artefacts
    await clearTestOrders(TEST_EMAIL);
    await clearTestUser(TEST_EMAIL);

    const ctx = await request.newContext({ baseURL: API_BASE });

    // 1. Register
    const regRes = await ctx.post('/api/v1/auth/register', {
      data: { name: 'Invoice Test User', email: TEST_EMAIL, password: TEST_PASSWORD, phone: '9000000002' }
    });
    expect(regRes.status()).toBe(201);

    // 2. Login — capture access_token cookie
    const loginRes = await ctx.post('/api/v1/auth/login', {
      data: { email: TEST_EMAIL, password: TEST_PASSWORD }
    });
    expect(loginRes.status()).toBe(200);
    const setCookieHeader = loginRes.headers()['set-cookie'] ?? '';
    const match = setCookieHeader.match(/access_token=([^;]+)/);
    expect(match, 'Login must set access_token cookie').not.toBeNull();
    authCookie = match![1];

    const authHeaders = { Authorization: `Bearer ${authCookie}` };

    const testProductId = await getSeededProductId('premium-cut-optics');

    // 3. Add product to cart
    const cartRes = await ctx.post('/api/v1/cart/items', {
      headers: { 
        'Authorization': `Bearer ${authCookie}`,
        'Cookie': `access_token=${authCookie}`,
        'Content-Type': 'application/json'
      },
      data: { product_id: Number(testProductId), quantity: 1 }
    });
    expect(cartRes.status()).toBe(200);

    // 4. Create order
    const orderRes = await ctx.post('/api/v1/orders', {
      headers: authHeaders,
      data: { shipping_address: '99 Receipt Road, Invoice City, NY 10001' }
    });
    expect(orderRes.status()).toBe(201);
    const orderData = (await orderRes.json()).data;
    const orderId: number = orderData.id;

    // 5. Create Razorpay payment intent
    const payRes = await ctx.post('/api/v1/payments/create-order', {
      headers: authHeaders,
      data: { order_id: orderId }
    });
    expect(payRes.status()).toBe(201);
    const payData = (await payRes.json()).data;
    const providerOrderId: string = payData.provider_order_id;

    // 6. Verify payment using the built-in mock signature bypass
    //    (payment_service.go line 266: "mock_signature_for_test" is always accepted)
    const verRes = await ctx.post('/api/v1/payments/verify', {
      headers: authHeaders,
      data: {
        razorpay_order_id: providerOrderId,
        razorpay_payment_id: 'pay_mock_e2e_invoice_test',
        razorpay_signature: 'mock_signature_for_test',
      }
    });
    expect(verRes.status(), 'Payment verification must succeed with mock signature').toBe(200);

    // 7. Fetch the invoice that was auto-generated by VerifyRazorpaySignature
    const invListRes = await ctx.get('/api/v1/invoices', { headers: authHeaders });
    expect(invListRes.status()).toBe(200);
    const invListData = (await invListRes.json()).data as Array<{ id: number }>;
    expect(invListData.length, 'At least one invoice must exist after payment').toBeGreaterThan(0);
    invoiceId = invListData[0].id;

    await ctx.dispose();
  });

  test.afterAll(async () => {
    await clearTestOrders(TEST_EMAIL);
    await clearTestUser(TEST_EMAIL);
  });

  // --------------------------------------------------------------------------
  // API-level test: invoice list is populated after payment
  // --------------------------------------------------------------------------
  test('API: Invoice list contains the generated invoice', async ({ request }) => {
    const res = await request.get(`${API_BASE}/api/v1/invoices`, {
      headers: { Authorization: `Bearer ${authCookie}` }
    });
    expect(res.status()).toBe(200);
    const body = await res.json();
    expect(body.success).toBe(true);
    expect(Array.isArray(body.data)).toBe(true);
    expect(body.data.length).toBeGreaterThan(0);

    const invoice = body.data[0];
    expect(invoice.id).toBeGreaterThan(0);
    expect(invoice.invoice_number).toMatch(/^INV-/);
    expect(invoice.status).toMatch(/PAID|PENDING/);
  });

  // --------------------------------------------------------------------------
  // API-level test: invoice download returns valid PDF bytes
  // --------------------------------------------------------------------------
  test('API: Invoice download returns HTTP 200 with application/pdf content', async ({ request }) => {
    expect(invoiceId, 'invoiceId must be set from beforeAll').toBeGreaterThan(0);

    const res = await request.get(`${API_BASE}/api/v1/invoices/${invoiceId}/download`, {
      headers: { Authorization: `Bearer ${authCookie}` }
    });

    expect(res.status()).toBe(200);

    // Verify content-type header
    const contentType = res.headers()['content-type'];
    expect(contentType).toContain('application/pdf');

    // Verify content-disposition signals a file download
    const disposition = res.headers()['content-disposition'];
    expect(disposition).toContain('attachment');
    expect(disposition).toContain('.pdf');

    // Verify the response body starts with the PDF magic bytes (%PDF-)
    const bodyBuffer = await res.body();
    expect(bodyBuffer.length).toBeGreaterThan(100);
    const pdfMagic = bodyBuffer.slice(0, 5).toString('ascii');
    expect(pdfMagic).toBe('%PDF-');
  });

  // --------------------------------------------------------------------------
  // API-level test: unauthenticated download is rejected
  // --------------------------------------------------------------------------
  test('API: Invoice download without auth returns 401', async ({ request }) => {
    const res = await request.get(`${API_BASE}/api/v1/invoices/${invoiceId}/download`);
    expect(res.status()).toBe(401);
  });

  // --------------------------------------------------------------------------
  // API-level test: download for a non-existent invoice returns 404
  // --------------------------------------------------------------------------
  test('API: Invoice download for missing ID returns 404', async ({ request }) => {
    const res = await request.get(`${API_BASE}/api/v1/invoices/999999/download`, {
      headers: { Authorization: `Bearer ${authCookie}` }
    });
    expect(res.status()).toBe(404);
  });

  // --------------------------------------------------------------------------
  // UI-level test: Account > Invoices tab shows invoice row and Download button
  // --------------------------------------------------------------------------
  test('UI: Account Invoices tab shows invoice row with Download button', async ({ page }) => {
    // Inject session cookie into the Playwright browser context
    await page.context().addCookies([{
      name: 'access_token',
      value: authCookie,
      domain: 'localhost',
      path: '/',
      httpOnly: true,
      secure: false,
    }]);

    await page.addInitScript((email) => {
      window.localStorage.setItem('eyeware_active_customer', JSON.stringify({
        id: 1,
        email: email,
        name: 'Invoice Test User'
      }));
    }, TEST_EMAIL);

    await page.goto('/');

    // Navigate to Account > Invoices
    const accountBtn = page.getByTitle('My Control Account Console').first();
    await accountBtn.click();
    await page.getByText('Invoices History', { exact: true }).click();

    // The invoice list should NOT show the empty state
    const emptyMsg = page.getByText(/No receipt invoices were generated/i);
    await expect(emptyMsg).toBeHidden({ timeout: 8000 });

    // A Download button must be visible
    const downloadBtn = page.getByText('Download Pdf').first();
    await expect(downloadBtn).toBeVisible({ timeout: 8000 });
  });

  // --------------------------------------------------------------------------
  // UI-level test: clicking Download triggers the file download
  // --------------------------------------------------------------------------
  test('UI: Clicking Download button initiates a PDF download', async ({ page }) => {
    await page.context().addCookies([{
      name: 'access_token',
      value: authCookie,
      domain: 'localhost',
      path: '/',
      httpOnly: true,
      secure: false,
    }]);

    await page.addInitScript((email) => {
      window.localStorage.setItem('eyeware_active_customer', JSON.stringify({
        id: 1,
        email: email,
        name: 'Invoice Test User'
      }));
    }, TEST_EMAIL);

    await page.goto('/');

    const accountBtn = page.getByTitle('My Control Account Console').first();
    await accountBtn.click();
    await page.getByText('Invoices History', { exact: true }).click();

    // Wait for list to render
    const downloadBtn = page.getByText('Download Pdf').first();
    await expect(downloadBtn).toBeVisible({ timeout: 8000 });

    // The target is _blank, so Playwright waitForEvent('popup') is needed if it opens a new tab.
    // However, it's an API download endpoint, which might trigger a download or just open a PDF.
    // Playwright handles target="_blank" + Content-Disposition: attachment by emitting both a popup and a download.
    // But sometimes it just opens a new page. Let's just listen for popup.
    const [popup] = await Promise.all([
      page.waitForEvent('popup', { timeout: 10000 }),
      downloadBtn.click(),
    ]);

    // Check if the URL points to a PDF file
    expect(popup.url()).toMatch(/\.pdf$/i);
  });
});
