// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: carts.sql

package sqlc

import (
	"time"

	"context"

	"github.com/google/uuid"
)

const clearCartItems = `-- name: ClearCartItems :exec
DELETE FROM cart_items
WHERE cart_id = $1
`

func (q *Queries) ClearCartItems(ctx context.Context, cartID int64) error {
	_, err := q.db.Exec(ctx, clearCartItems, cartID)
	return err
}

const createCart = `-- name: CreateCart :one
INSERT INTO carts (user_id)
VALUES ($1)
RETURNING id, user_id, created_at, updated_at
`

func (q *Queries) CreateCart(ctx context.Context, userID uuid.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCartItem = `-- name: CreateCartItem :one
INSERT INTO cart_items (cart_id, product_id, quantity)
VALUES ($1, $2, $3)
RETURNING id, cart_id, product_id, quantity, created_at, updated_at
`

type CreateCartItemParams struct {
	CartID    int64 `json:"cart_id"`
	ProductID int64 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
}

func (q *Queries) CreateCartItem(ctx context.Context, arg CreateCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, createCartItem, arg.CartID, arg.ProductID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart_items
WHERE id = $1 AND cart_id = $2
`

type DeleteCartItemParams struct {
	ID     int64 `json:"id"`
	CartID int64 `json:"cart_id"`
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error {
	_, err := q.db.Exec(ctx, deleteCartItem, arg.ID, arg.CartID)
	return err
}

const getCartByUserID = `-- name: GetCartByUserID :one
SELECT id, user_id, created_at, updated_at
FROM carts
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetCartByUserID(ctx context.Context, userID uuid.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByUserID, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItemByID = `-- name: GetCartItemByID :one
SELECT id, cart_id, product_id, quantity, created_at, updated_at
FROM cart_items
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCartItemByID(ctx context.Context, id int64) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItemByID, id)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItemByProduct = `-- name: GetCartItemByProduct :one
SELECT id, cart_id, product_id, quantity, created_at, updated_at
FROM cart_items
WHERE cart_id = $1 AND product_id = $2 LIMIT 1
`

type GetCartItemByProductParams struct {
	CartID    int64 `json:"cart_id"`
	ProductID int64 `json:"product_id"`
}

func (q *Queries) GetCartItemByProduct(ctx context.Context, arg GetCartItemByProductParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItemByProduct, arg.CartID, arg.ProductID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCartItemsDetailed = `-- name: ListCartItemsDetailed :many
SELECT 
    ci.id, 
    ci.cart_id, 
    ci.product_id, 
    ci.quantity, 
    ci.created_at, 
    ci.updated_at,
    p.name AS product_name,
    p.price AS product_price,
    p.sale_price AS product_sale_price,
    p.slug AS product_slug,
    p.brand AS product_brand,
    p.stock AS product_stock
FROM cart_items ci
JOIN products p ON ci.product_id = p.id
WHERE ci.cart_id = $1
ORDER BY ci.created_at ASC
`

type ListCartItemsDetailedRow struct {
	ID               int64              `json:"id"`
	CartID           int64              `json:"cart_id"`
	ProductID        int64              `json:"product_id"`
	Quantity         int32              `json:"quantity"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	ProductName      string             `json:"product_name"`
	ProductPrice     float64            `json:"product_price"`
	ProductSalePrice *float64     `json:"product_sale_price"`
	ProductSlug      string             `json:"product_slug"`
	ProductBrand     string             `json:"product_brand"`
	ProductStock     int32              `json:"product_stock"`
}

func (q *Queries) ListCartItemsDetailed(ctx context.Context, cartID int64) ([]ListCartItemsDetailedRow, error) {
	rows, err := q.db.Query(ctx, listCartItemsDetailed, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCartItemsDetailedRow
	for rows.Next() {
		var i ListCartItemsDetailedRow
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductName,
			&i.ProductPrice,
			&i.ProductSalePrice,
			&i.ProductSlug,
			&i.ProductBrand,
			&i.ProductStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE cart_items
SET quantity = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, cart_id, product_id, quantity, created_at, updated_at
`

type UpdateCartItemQuantityParams struct {
	ID       int64 `json:"id"`
	Quantity int32 `json:"quantity"`
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItemQuantity, arg.ID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
