// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: invoices.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
  order_id, invoice_number, invoice_url, status
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, order_id, invoice_number, invoice_url, status, created_at
`

type CreateInvoiceParams struct {
	OrderID       int64  `json:"order_id"`
	InvoiceNumber string `json:"invoice_number"`
	InvoiceUrl    string `json:"invoice_url"`
	Status        string `json:"status"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.OrderID,
		arg.InvoiceNumber,
		arg.InvoiceUrl,
		arg.Status,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.InvoiceNumber,
		&i.InvoiceUrl,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, order_id, invoice_number, invoice_url, status, created_at
FROM invoices
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetInvoiceByID(ctx context.Context, id int64) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.InvoiceNumber,
		&i.InvoiceUrl,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoiceByIDAndUserID = `-- name: GetInvoiceByIDAndUserID :one
SELECT i.id, i.order_id, i.invoice_number, i.invoice_url, i.status, i.created_at
FROM invoices i
JOIN orders o ON i.order_id = o.id
WHERE i.id = $1 AND o.user_id = $2 LIMIT 1
`

type GetInvoiceByIDAndUserIDParams struct {
	ID     int64     `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetInvoiceByIDAndUserID(ctx context.Context, arg GetInvoiceByIDAndUserIDParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByIDAndUserID, arg.ID, arg.UserID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.InvoiceNumber,
		&i.InvoiceUrl,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoiceByOrderID = `-- name: GetInvoiceByOrderID :one
SELECT id, order_id, invoice_number, invoice_url, status, created_at
FROM invoices
WHERE order_id = $1 LIMIT 1
`

func (q *Queries) GetInvoiceByOrderID(ctx context.Context, orderID int64) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByOrderID, orderID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.InvoiceNumber,
		&i.InvoiceUrl,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listAllInvoices = `-- name: ListAllInvoices :many
SELECT id, order_id, invoice_number, invoice_url, status, created_at
FROM invoices
ORDER BY created_at DESC
`

func (q *Queries) ListAllInvoices(ctx context.Context) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listAllInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.InvoiceNumber,
			&i.InvoiceUrl,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByUserID = `-- name: ListInvoicesByUserID :many
SELECT i.id, i.order_id, i.invoice_number, i.invoice_url, i.status, i.created_at
FROM invoices i
JOIN orders o ON i.order_id = o.id
WHERE o.user_id = $1
ORDER BY i.created_at DESC
`

func (q *Queries) ListInvoicesByUserID(ctx context.Context, userID uuid.UUID) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.InvoiceNumber,
			&i.InvoiceUrl,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :one
UPDATE invoices
SET status = $2
WHERE id = $1
RETURNING id, order_id, invoice_number, invoice_url, status, created_at
`

type UpdateInvoiceStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoiceStatus, arg.ID, arg.Status)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.InvoiceNumber,
		&i.InvoiceUrl,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
