// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Cart struct {
	ID        int64              `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type CartItem struct {
	ID        int64              `json:"id"`
	CartID    int64              `json:"cart_id"`
	ProductID int64              `json:"product_id"`
	Quantity  int32              `json:"quantity"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Category struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description *string            `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Invoice struct {
	ID            int64              `json:"id"`
	OrderID       int64              `json:"order_id"`
	InvoiceNumber string             `json:"invoice_number"`
	InvoiceUrl    string             `json:"invoice_url"`
	Status        string             `json:"status"`
	CreatedAt     time.Time `json:"created_at"`
}

type Order struct {
	ID              int64              `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Status          string             `json:"status"`
	TotalAmount     float64            `json:"total_amount"`
	TrackingNumber  *string            `json:"tracking_number"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	ShippingAddress string             `json:"shipping_address"`
}

type OrderItem struct {
	ID              int64   `json:"id"`
	OrderID         int64   `json:"order_id"`
	ProductID       int64   `json:"product_id"`
	Quantity        int32   `json:"quantity"`
	Price           float64 `json:"price"`
	ProductSnapshot []byte  `json:"product_snapshot"`
}

type Payment struct {
	ID                int64              `json:"id"`
	OrderID           int64              `json:"order_id"`
	UserID            uuid.UUID          `json:"user_id"`
	Provider          string             `json:"provider"`
	ProviderOrderID   string             `json:"provider_order_id"`
	ProviderPaymentID *string            `json:"provider_payment_id"`
	Amount            float64            `json:"amount"`
	Status            string             `json:"status"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type Prescription struct {
	ID               int64              `json:"id"`
	OrderID          int64              `json:"order_id"`
	UserID           uuid.UUID          `json:"user_id"`
	PrescriptionType string             `json:"prescription_type"`
	FileUrl          string             `json:"file_url"`
	ObjectKey        string             `json:"object_key"`
	Notes            *string            `json:"notes"`
	Status           string             `json:"status"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type Product struct {
	ID          int64              `json:"id"`
	CategoryID  *int64             `json:"category_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description string             `json:"description"`
	Price       float64            `json:"price"`
	SalePrice   *float64     `json:"sale_price"`
	Brand       string             `json:"brand"`
	FrameType   string             `json:"frame_type"`
	Material    string             `json:"material"`
	Gender      string             `json:"gender"`
	Stock       int32              `json:"stock"`
	Status      string             `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ProductImage struct {
	ID        int64              `json:"id"`
	ProductID int64              `json:"product_id"`
	ImageUrl  string             `json:"image_url"`
	IsPrimary bool               `json:"is_primary"`
	CreatedAt time.Time `json:"created_at"`
	ObjectKey *string            `json:"object_key"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	Phone        *string            `json:"phone"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
