// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: orders.sql

package sqlc

import (
	"time"

	"context"

	"github.com/google/uuid"
)

const adminGetOrderDetails = `-- name: AdminGetOrderDetails :one
SELECT o.id, o.user_id, o.status, o.total_amount, o.tracking_number, o.shipping_address, o.created_at, o.updated_at, u.name as user_name, u.email as user_email
FROM orders o
JOIN users u ON o.user_id = u.id
WHERE o.id = $1 LIMIT 1
`

type AdminGetOrderDetailsRow struct {
	ID              int64              `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Status          string             `json:"status"`
	TotalAmount     float64            `json:"total_amount"`
	TrackingNumber  *string            `json:"tracking_number"`
	ShippingAddress string             `json:"shipping_address"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	UserName        string             `json:"user_name"`
	UserEmail       string             `json:"user_email"`
}

func (q *Queries) AdminGetOrderDetails(ctx context.Context, id int64) (AdminGetOrderDetailsRow, error) {
	row := q.db.QueryRow(ctx, adminGetOrderDetails, id)
	var i AdminGetOrderDetailsRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.TrackingNumber,
		&i.ShippingAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserEmail,
	)
	return i, err
}

const adminListOrdersPaged = `-- name: AdminListOrdersPaged :many
SELECT o.id, o.user_id, o.status, o.total_amount, o.tracking_number, o.shipping_address, o.created_at, o.updated_at, u.name as user_name, u.email as user_email  
FROM orders o  
JOIN users u ON o.user_id = u.id  
ORDER BY o.created_at DESC  
LIMIT $1 OFFSET $2
`

type AdminListOrdersPagedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type AdminListOrdersPagedRow struct {
	ID              int64              `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Status          string             `json:"status"`
	TotalAmount     float64            `json:"total_amount"`
	TrackingNumber  *string            `json:"tracking_number"`
	ShippingAddress string             `json:"shipping_address"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	UserName        string             `json:"user_name"`
	UserEmail       string             `json:"user_email"`
}

func (q *Queries) AdminListOrdersPaged(ctx context.Context, arg AdminListOrdersPagedParams) ([]AdminListOrdersPagedRow, error) {
	rows, err := q.db.Query(ctx, adminListOrdersPaged, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListOrdersPagedRow
	for rows.Next() {
		var i AdminListOrdersPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalAmount,
			&i.TrackingNumber,
			&i.ShippingAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
  user_id, status, total_amount, tracking_number, shipping_address
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, user_id, status, total_amount, tracking_number, created_at, updated_at, shipping_address
`

type CreateOrderParams struct {
	UserID          uuid.UUID `json:"user_id"`
	Status          string    `json:"status"`
	TotalAmount     float64   `json:"total_amount"`
	TrackingNumber  *string   `json:"tracking_number"`
	ShippingAddress string    `json:"shipping_address"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.Status,
		arg.TotalAmount,
		arg.TrackingNumber,
		arg.ShippingAddress,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.TrackingNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShippingAddress,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
  order_id, product_id, quantity, price, product_snapshot
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, order_id, product_id, quantity, price, product_snapshot
`

type CreateOrderItemParams struct {
	OrderID         int64   `json:"order_id"`
	ProductID       int64   `json:"product_id"`
	Quantity        int32   `json:"quantity"`
	Price           float64 `json:"price"`
	ProductSnapshot []byte  `json:"product_snapshot"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
		arg.ProductSnapshot,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
		&i.ProductSnapshot,
	)
	return i, err
}

const decrementProductStock = `-- name: DecrementProductStock :execrows
UPDATE products
SET stock = stock - $2, updated_at = NOW()
WHERE id = $1 AND stock >= $2
`

type DecrementProductStockParams struct {
	ID    int64 `json:"id"`
	Stock int32 `json:"stock"`
}

func (q *Queries) DecrementProductStock(ctx context.Context, arg DecrementProductStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, decrementProductStock, arg.ID, arg.Stock)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, status, total_amount, tracking_number, created_at, updated_at, shipping_address
FROM orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.TrackingNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShippingAddress,
	)
	return i, err
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT id, order_id, product_id, quantity, price, product_snapshot
FROM order_items
WHERE order_id = $1
ORDER BY id ASC
`

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID int64) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.Price,
			&i.ProductSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUserID = `-- name: ListOrdersByUserID :many
SELECT id, user_id, status, total_amount, tracking_number, created_at, updated_at, shipping_address
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByUserID(ctx context.Context, userID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalAmount,
			&i.TrackingNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShippingAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUserIDPaged = `-- name: ListOrdersByUserIDPaged :many
SELECT id, user_id, status, total_amount, tracking_number, created_at, updated_at, shipping_address
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByUserIDPagedParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListOrdersByUserIDPaged(ctx context.Context, arg ListOrdersByUserIDPagedParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUserIDPaged, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalAmount,
			&i.TrackingNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShippingAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersPaged = `-- name: ListOrdersPaged :many
SELECT id, user_id, status, total_amount, tracking_number, created_at, updated_at, shipping_address
FROM orders
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListOrdersPagedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOrdersPaged(ctx context.Context, arg ListOrdersPagedParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersPaged, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalAmount,
			&i.TrackingNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShippingAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, status, total_amount, tracking_number, created_at, updated_at, shipping_address
`

type UpdateOrderStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.TrackingNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShippingAddress,
	)
	return i, err
}
