// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
  order_id, user_id, provider, provider_order_id, provider_payment_id, amount, status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, order_id, user_id, provider, provider_order_id, provider_payment_id, amount, status, created_at, updated_at
`

type CreatePaymentParams struct {
	OrderID           int64     `json:"order_id"`
	UserID            uuid.UUID `json:"user_id"`
	Provider          string    `json:"provider"`
	ProviderOrderID   string    `json:"provider_order_id"`
	ProviderPaymentID *string   `json:"provider_payment_id"`
	Amount            float64   `json:"amount"`
	Status            string    `json:"status"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.UserID,
		arg.Provider,
		arg.ProviderOrderID,
		arg.ProviderPaymentID,
		arg.Amount,
		arg.Status,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.Provider,
		&i.ProviderOrderID,
		&i.ProviderPaymentID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, order_id, user_id, provider, provider_order_id, provider_payment_id, amount, status, created_at, updated_at
FROM payments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.Provider,
		&i.ProviderOrderID,
		&i.ProviderPaymentID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByProviderOrderID = `-- name: GetPaymentByProviderOrderID :one
SELECT id, order_id, user_id, provider, provider_order_id, provider_payment_id, amount, status, created_at, updated_at
FROM payments
WHERE provider_order_id = $1 LIMIT 1
`

func (q *Queries) GetPaymentByProviderOrderID(ctx context.Context, providerOrderID string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByProviderOrderID, providerOrderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.Provider,
		&i.ProviderOrderID,
		&i.ProviderPaymentID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByProviderPaymentID = `-- name: GetPaymentByProviderPaymentID :one
SELECT id, order_id, user_id, provider, provider_order_id, provider_payment_id, amount, status, created_at, updated_at
FROM payments
WHERE provider_payment_id = $1 LIMIT 1
`

func (q *Queries) GetPaymentByProviderPaymentID(ctx context.Context, providerPaymentID *string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByProviderPaymentID, providerPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.Provider,
		&i.ProviderOrderID,
		&i.ProviderPaymentID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentsByUserID = `-- name: ListPaymentsByUserID :many
SELECT id, order_id, user_id, provider, provider_order_id, provider_payment_id, amount, status, created_at, updated_at
FROM payments
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPaymentsByUserID(ctx context.Context, userID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.UserID,
			&i.Provider,
			&i.ProviderOrderID,
			&i.ProviderPaymentID,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, order_id, user_id, provider, provider_order_id, provider_payment_id, amount, status, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.ID, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.Provider,
		&i.ProviderOrderID,
		&i.ProviderPaymentID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatusAndPaymentID = `-- name: UpdatePaymentStatusAndPaymentID :one
UPDATE payments
SET status = $2, provider_payment_id = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, order_id, user_id, provider, provider_order_id, provider_payment_id, amount, status, created_at, updated_at
`

type UpdatePaymentStatusAndPaymentIDParams struct {
	ID                int64   `json:"id"`
	Status            string  `json:"status"`
	ProviderPaymentID *string `json:"provider_payment_id"`
}

func (q *Queries) UpdatePaymentStatusAndPaymentID(ctx context.Context, arg UpdatePaymentStatusAndPaymentIDParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatusAndPaymentID, arg.ID, arg.Status, arg.ProviderPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.Provider,
		&i.ProviderOrderID,
		&i.ProviderPaymentID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
