// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: prescriptions.sql

package sqlc

import (
	"time"

	"context"

	"github.com/google/uuid"
)

const adminGetPrescriptionByID = `-- name: AdminGetPrescriptionByID :one
SELECT p.id, p.order_id, p.user_id, p.prescription_type, p.file_url, p.object_key, p.notes, p.status, p.created_at, p.updated_at, u.name as user_name, u.email as user_email
FROM prescriptions p
JOIN users u ON p.user_id = u.id
WHERE p.id = $1 LIMIT 1
`

type AdminGetPrescriptionByIDRow struct {
	ID               int64              `json:"id"`
	OrderID          int64              `json:"order_id"`
	UserID           uuid.UUID          `json:"user_id"`
	PrescriptionType string             `json:"prescription_type"`
	FileUrl          string             `json:"file_url"`
	ObjectKey        string             `json:"object_key"`
	Notes            *string            `json:"notes"`
	Status           string             `json:"status"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	UserName         string             `json:"user_name"`
	UserEmail        string             `json:"user_email"`
}

func (q *Queries) AdminGetPrescriptionByID(ctx context.Context, id int64) (AdminGetPrescriptionByIDRow, error) {
	row := q.db.QueryRow(ctx, adminGetPrescriptionByID, id)
	var i AdminGetPrescriptionByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.PrescriptionType,
		&i.FileUrl,
		&i.ObjectKey,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserEmail,
	)
	return i, err
}

const adminListAllPrescriptions = `-- name: AdminListAllPrescriptions :many
SELECT p.id, p.order_id, p.user_id, p.prescription_type, p.file_url, p.object_key, p.notes, p.status, p.created_at, p.updated_at, u.name as user_name, u.email as user_email
FROM prescriptions p
JOIN users u ON p.user_id = u.id
ORDER BY p.created_at DESC
`

type AdminListAllPrescriptionsRow struct {
	ID               int64              `json:"id"`
	OrderID          int64              `json:"order_id"`
	UserID           uuid.UUID          `json:"user_id"`
	PrescriptionType string             `json:"prescription_type"`
	FileUrl          string             `json:"file_url"`
	ObjectKey        string             `json:"object_key"`
	Notes            *string            `json:"notes"`
	Status           string             `json:"status"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	UserName         string             `json:"user_name"`
	UserEmail        string             `json:"user_email"`
}

func (q *Queries) AdminListAllPrescriptions(ctx context.Context) ([]AdminListAllPrescriptionsRow, error) {
	rows, err := q.db.Query(ctx, adminListAllPrescriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListAllPrescriptionsRow
	for rows.Next() {
		var i AdminListAllPrescriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.UserID,
			&i.PrescriptionType,
			&i.FileUrl,
			&i.ObjectKey,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createPrescription = `-- name: CreatePrescription :one
INSERT INTO prescriptions (
  order_id, user_id, prescription_type, file_url, object_key, notes, status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, order_id, user_id, prescription_type, file_url, object_key, notes, status, created_at, updated_at
`

type CreatePrescriptionParams struct {
	OrderID          int64     `json:"order_id"`
	UserID           uuid.UUID `json:"user_id"`
	PrescriptionType string    `json:"prescription_type"`
	FileUrl          string    `json:"file_url"`
	ObjectKey        string    `json:"object_key"`
	Notes            *string   `json:"notes"`
	Status           string    `json:"status"`
}

func (q *Queries) CreatePrescription(ctx context.Context, arg CreatePrescriptionParams) (Prescription, error) {
	row := q.db.QueryRow(ctx, createPrescription,
		arg.OrderID,
		arg.UserID,
		arg.PrescriptionType,
		arg.FileUrl,
		arg.ObjectKey,
		arg.Notes,
		arg.Status,
	)
	var i Prescription
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.PrescriptionType,
		&i.FileUrl,
		&i.ObjectKey,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrescriptionByID = `-- name: GetPrescriptionByID :one
SELECT id, order_id, user_id, prescription_type, file_url, object_key, notes, status, created_at, updated_at
FROM prescriptions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPrescriptionByID(ctx context.Context, id int64) (Prescription, error) {
	row := q.db.QueryRow(ctx, getPrescriptionByID, id)
	var i Prescription
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.PrescriptionType,
		&i.FileUrl,
		&i.ObjectKey,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrescriptionByIDAndUserID = `-- name: GetPrescriptionByIDAndUserID :one
SELECT id, order_id, user_id, prescription_type, file_url, object_key, notes, status, created_at, updated_at
FROM prescriptions
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetPrescriptionByIDAndUserIDParams struct {
	ID     int64     `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetPrescriptionByIDAndUserID(ctx context.Context, arg GetPrescriptionByIDAndUserIDParams) (Prescription, error) {
	row := q.db.QueryRow(ctx, getPrescriptionByIDAndUserID, arg.ID, arg.UserID)
	var i Prescription
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.PrescriptionType,
		&i.FileUrl,
		&i.ObjectKey,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPrescriptions = `-- name: ListAllPrescriptions :many
SELECT id, order_id, user_id, prescription_type, file_url, object_key, notes, status, created_at, updated_at
FROM prescriptions
ORDER BY created_at DESC
`

func (q *Queries) ListAllPrescriptions(ctx context.Context) ([]Prescription, error) {
	rows, err := q.db.Query(ctx, listAllPrescriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prescription
	for rows.Next() {
		var i Prescription
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.UserID,
			&i.PrescriptionType,
			&i.FileUrl,
			&i.ObjectKey,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionsByOrderID = `-- name: ListPrescriptionsByOrderID :many
SELECT id, order_id, user_id, prescription_type, file_url, object_key, notes, status, created_at, updated_at
FROM prescriptions
WHERE order_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPrescriptionsByOrderID(ctx context.Context, orderID int64) ([]Prescription, error) {
	rows, err := q.db.Query(ctx, listPrescriptionsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prescription
	for rows.Next() {
		var i Prescription
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.UserID,
			&i.PrescriptionType,
			&i.FileUrl,
			&i.ObjectKey,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionsByUserID = `-- name: ListPrescriptionsByUserID :many
SELECT id, order_id, user_id, prescription_type, file_url, object_key, notes, status, created_at, updated_at
FROM prescriptions
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPrescriptionsByUserID(ctx context.Context, userID uuid.UUID) ([]Prescription, error) {
	rows, err := q.db.Query(ctx, listPrescriptionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prescription
	for rows.Next() {
		var i Prescription
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.UserID,
			&i.PrescriptionType,
			&i.FileUrl,
			&i.ObjectKey,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrescriptionStatus = `-- name: UpdatePrescriptionStatus :one
UPDATE prescriptions
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, order_id, user_id, prescription_type, file_url, object_key, notes, status, created_at, updated_at
`

type UpdatePrescriptionStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdatePrescriptionStatus(ctx context.Context, arg UpdatePrescriptionStatusParams) (Prescription, error) {
	row := q.db.QueryRow(ctx, updatePrescriptionStatus, arg.ID, arg.Status)
	var i Prescription
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.PrescriptionType,
		&i.FileUrl,
		&i.ObjectKey,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
