// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: products.sql

package sqlc

import (
	"context"

)

const clearPrimaryProductImage = `-- name: ClearPrimaryProductImage :exec
UPDATE product_images
SET is_primary = false
WHERE product_id = $1
`

func (q *Queries) ClearPrimaryProductImage(ctx context.Context, productID int64) error {
	_, err := q.db.Exec(ctx, clearPrimaryProductImage, productID)
	return err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, slug, description)
VALUES ($1, $2, $3)
RETURNING id, name, slug, description, created_at, updated_at
`

type CreateCategoryParams struct {
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	Description *string `json:"description"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Slug, arg.Description)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  category_id, name, slug, description, price, sale_price, brand, frame_type, material, gender, stock, status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, category_id, name, slug, description, price, sale_price, brand, frame_type, material, gender, stock, status, created_at, updated_at
`

type CreateProductParams struct {
	CategoryID  *int64         `json:"category_id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description string         `json:"description"`
	Price       float64        `json:"price"`
	SalePrice   *float64 `json:"sale_price"`
	Brand       string         `json:"brand"`
	FrameType   string         `json:"frame_type"`
	Material    string         `json:"material"`
	Gender      string         `json:"gender"`
	Stock       int32          `json:"stock"`
	Status      string         `json:"status"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Price,
		arg.SalePrice,
		arg.Brand,
		arg.FrameType,
		arg.Material,
		arg.Gender,
		arg.Stock,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.SalePrice,
		&i.Brand,
		&i.FrameType,
		&i.Material,
		&i.Gender,
		&i.Stock,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product_images (product_id, image_url, object_key, is_primary)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, image_url, is_primary, created_at, object_key
`

type CreateProductImageParams struct {
	ProductID int64   `json:"product_id"`
	ImageUrl  string  `json:"image_url"`
	ObjectKey *string `json:"object_key"`
	IsPrimary bool    `json:"is_primary"`
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, createProductImage,
		arg.ProductID,
		arg.ImageUrl,
		arg.ObjectKey,
		arg.IsPrimary,
	)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ImageUrl,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.ObjectKey,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const deleteProductImageByID = `-- name: DeleteProductImageByID :exec
DELETE FROM product_images
WHERE id = $1 AND product_id = $2
`

type DeleteProductImageByIDParams struct {
	ID        int64 `json:"id"`
	ProductID int64 `json:"product_id"`
}

func (q *Queries) DeleteProductImageByID(ctx context.Context, arg DeleteProductImageByIDParams) error {
	_, err := q.db.Exec(ctx, deleteProductImageByID, arg.ID, arg.ProductID)
	return err
}

const deleteProductImagesByProductID = `-- name: DeleteProductImagesByProductID :exec
DELETE FROM product_images WHERE product_id = $1
`

func (q *Queries) DeleteProductImagesByProductID(ctx context.Context, productID int64) error {
	_, err := q.db.Exec(ctx, deleteProductImagesByProductID, productID)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, slug, description, created_at, updated_at 
FROM categories 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, name, slug, description, created_at, updated_at 
FROM categories 
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, category_id, name, slug, description, price, sale_price, brand, frame_type, material, gender, stock, status, created_at, updated_at
FROM products 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.SalePrice,
		&i.Brand,
		&i.FrameType,
		&i.Material,
		&i.Gender,
		&i.Stock,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, category_id, name, slug, description, price, sale_price, brand, frame_type, material, gender, stock, status, created_at, updated_at
FROM products 
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.SalePrice,
		&i.Brand,
		&i.FrameType,
		&i.Material,
		&i.Gender,
		&i.Stock,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductImageByID = `-- name: GetProductImageByID :one
SELECT id, product_id, image_url, is_primary, created_at, object_key
FROM product_images
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProductImageByID(ctx context.Context, id int64) (ProductImage, error) {
	row := q.db.QueryRow(ctx, getProductImageByID, id)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ImageUrl,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.ObjectKey,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, description, created_at, updated_at 
FROM categories 
ORDER BY name ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductImagesByProductID = `-- name: ListProductImagesByProductID :many
SELECT id, product_id, image_url, is_primary, created_at, object_key 
FROM product_images 
WHERE product_id = $1 
ORDER BY is_primary DESC, id ASC
`

func (q *Queries) ListProductImagesByProductID(ctx context.Context, productID int64) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, listProductImagesByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductImage
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ImageUrl,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.ObjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsLimited = `-- name: ListProductsLimited :many
SELECT id, category_id, name, slug, description, price, sale_price, brand, frame_type, material, gender, stock, status, created_at, updated_at
FROM products
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsLimitedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProductsLimited(ctx context.Context, arg ListProductsLimitedParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsLimited, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.SalePrice,
			&i.Brand,
			&i.FrameType,
			&i.Material,
			&i.Gender,
			&i.Stock,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = COALESCE($2, name),
    slug = COALESCE($3, slug),
    description = COALESCE($4, description),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, description, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID          int64   `json:"id"`
	Name        *string `json:"name"`
	Slug        *string `json:"slug"`
	Description *string `json:"description"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET category_id = COALESCE($2, category_id),
    name = COALESCE($3, name),
    slug = COALESCE($4, slug),
    description = COALESCE($5, description),
    price = COALESCE($6, price),
    sale_price = COALESCE($7, sale_price),
    brand = COALESCE($8, brand),
    frame_type = COALESCE($9, frame_type),
    material = COALESCE($10, material),
    gender = COALESCE($11, gender),
    stock = COALESCE($12, stock),
    status = COALESCE($13, status),
    updated_at = NOW()
WHERE id = $1
RETURNING id, category_id, name, slug, description, price, sale_price, brand, frame_type, material, gender, stock, status, created_at, updated_at
`

type UpdateProductParams struct {
	ID          int64          `json:"id"`
	CategoryID  *int64         `json:"category_id"`
	Name        *string        `json:"name"`
	Slug        *string        `json:"slug"`
	Description *string        `json:"description"`
	Price       *float64 `json:"price"`
	SalePrice   *float64 `json:"sale_price"`
	Brand       *string        `json:"brand"`
	FrameType   *string        `json:"frame_type"`
	Material    *string        `json:"material"`
	Gender      *string        `json:"gender"`
	Stock       *int32         `json:"stock"`
	Status      *string        `json:"status"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Price,
		arg.SalePrice,
		arg.Brand,
		arg.FrameType,
		arg.Material,
		arg.Gender,
		arg.Stock,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.SalePrice,
		&i.Brand,
		&i.FrameType,
		&i.Material,
		&i.Gender,
		&i.Stock,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
