// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AdminGetOrderDetails(ctx context.Context, id int64) (AdminGetOrderDetailsRow, error)
	AdminGetPrescriptionByID(ctx context.Context, id int64) (AdminGetPrescriptionByIDRow, error)
	AdminListAllPrescriptions(ctx context.Context) ([]AdminListAllPrescriptionsRow, error)
	AdminListOrdersPaged(ctx context.Context, arg AdminListOrdersPagedParams) ([]AdminListOrdersPagedRow, error)
	ClearCartItems(ctx context.Context, cartID int64) error
	ClearPrimaryProductImage(ctx context.Context, productID int64) error
	CreateCart(ctx context.Context, userID uuid.UUID) (Cart, error)
	CreateCartItem(ctx context.Context, arg CreateCartItemParams) (CartItem, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePrescription(ctx context.Context, arg CreatePrescriptionParams) (Prescription, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecrementProductStock(ctx context.Context, arg DecrementProductStockParams) (int64, error)
	DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error
	DeleteCategory(ctx context.Context, id int64) error
	DeleteProduct(ctx context.Context, id int64) error
	DeleteProductImageByID(ctx context.Context, arg DeleteProductImageByIDParams) error
	DeleteProductImagesByProductID(ctx context.Context, productID int64) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetCartByUserID(ctx context.Context, userID uuid.UUID) (Cart, error)
	GetCartItemByID(ctx context.Context, id int64) (CartItem, error)
	GetCartItemByProduct(ctx context.Context, arg GetCartItemByProductParams) (CartItem, error)
	GetCategoryByID(ctx context.Context, id int64) (Category, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetInvoiceByID(ctx context.Context, id int64) (Invoice, error)
	GetInvoiceByIDAndUserID(ctx context.Context, arg GetInvoiceByIDAndUserIDParams) (Invoice, error)
	GetInvoiceByOrderID(ctx context.Context, orderID int64) (Invoice, error)
	GetOrderByID(ctx context.Context, id int64) (Order, error)
	GetPaymentByID(ctx context.Context, id int64) (Payment, error)
	GetPaymentByProviderOrderID(ctx context.Context, providerOrderID string) (Payment, error)
	GetPaymentByProviderPaymentID(ctx context.Context, providerPaymentID *string) (Payment, error)
	GetPrescriptionByID(ctx context.Context, id int64) (Prescription, error)
	GetPrescriptionByIDAndUserID(ctx context.Context, arg GetPrescriptionByIDAndUserIDParams) (Prescription, error)
	GetProductByID(ctx context.Context, id int64) (Product, error)
	GetProductBySlug(ctx context.Context, slug string) (Product, error)
	GetProductImageByID(ctx context.Context, id int64) (ProductImage, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListAllInvoices(ctx context.Context) ([]Invoice, error)
	ListAllPrescriptions(ctx context.Context) ([]Prescription, error)
	ListCartItemsDetailed(ctx context.Context, cartID int64) ([]ListCartItemsDetailedRow, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListInvoicesByUserID(ctx context.Context, userID uuid.UUID) ([]Invoice, error)
	ListOrderItemsByOrderID(ctx context.Context, orderID int64) ([]OrderItem, error)
	ListOrdersByUserID(ctx context.Context, userID uuid.UUID) ([]Order, error)
	ListOrdersByUserIDPaged(ctx context.Context, arg ListOrdersByUserIDPagedParams) ([]Order, error)
	ListOrdersPaged(ctx context.Context, arg ListOrdersPagedParams) ([]Order, error)
	ListPaymentsByUserID(ctx context.Context, userID uuid.UUID) ([]Payment, error)
	ListPrescriptionsByOrderID(ctx context.Context, orderID int64) ([]Prescription, error)
	ListPrescriptionsByUserID(ctx context.Context, userID uuid.UUID) ([]Prescription, error)
	ListProductImagesByProductID(ctx context.Context, productID int64) ([]ProductImage, error)
	ListProductsLimited(ctx context.Context, arg ListProductsLimitedParams) ([]Product, error)
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdatePaymentStatusAndPaymentID(ctx context.Context, arg UpdatePaymentStatusAndPaymentIDParams) (Payment, error)
	UpdatePrescriptionStatus(ctx context.Context, arg UpdatePrescriptionStatusParams) (Prescription, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
